//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Member.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Memb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Memb()
        {
            this.Collection = new HashSet<Collection>();
            this.Mes = new HashSet<Mes>();
            this.MesR = new HashSet<MesR>();
            this.MesS = new HashSet<MesS>();
        }
    
        public int UsId { get; set; }
        public string UsEmail { get; set; }       
        public string UsPassword { get; set; }
        public string UsName { get; set; }
        public Nullable<bool> UsSex { get; set; }
        public string UsPh { get; set; }
        public Nullable<System.DateTime> UsJnD { get; set; }
        public bool UsVdS { get; set; }
        public Nullable<int> ITId { get; set; }
        public bool UsLks { get; set; }
        public Nullable<System.DateTime> UsLkT { get; set; }
        public Nullable<System.DateTime> UsULkT { get; set; }
        public int UsLkc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collection> Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mes> Mes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesR> MesR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesS> MesS { get; set; }
    }
}
