//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Member.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mes()
        {
            this.MesR = new HashSet<MesR>();
            this.MesS = new HashSet<MesS>();
        }
    
        public int MsId { get; set; }
        public int MsP { get; set; }
        public int MsR { get; set; }
        public int UsId { get; set; }
        public int StId { get; set; }
        public System.DateTime MsDate { get; set; }
        public string MsCont { get; set; }
        public int MsGC { get; set; }
        public int MsBC { get; set; }
        public Nullable<bool> MsRpt { get; set; }
        public Nullable<bool> MsE { get; set; }
    
        public virtual Memb Memb { get; set; }
        public virtual Stock Stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesR> MesR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesS> MesS { get; set; }
    }
}
