//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Member.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UsersEntities : DbContext
    {
        public UsersEntities()
            : base("name=UsersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arti> Arti { get; set; }
        public virtual DbSet<Collection> Collection { get; set; }
        public virtual DbSet<Industry> Industry { get; set; }
        public virtual DbSet<IndustryD> IndustryD { get; set; }
        public virtual DbSet<Mager> Mager { get; set; }
        public virtual DbSet<Memb> Memb { get; set; }
        public virtual DbSet<Mes> Mes { get; set; }
        public virtual DbSet<MesR> MesR { get; set; }
        public virtual DbSet<MesS> MesS { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
    }
}
